config/routes.rb
Rails.application.routes.draw do
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :text, :image_url, :string, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bootcont</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <nav class="navbar navbar-success">
  
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/">Typos</a></li>
      <li><a href="/static_pages/home">home</a></li>
      <li><a href="/static_pages/help">help</a></li>
      <li><a href="/static_pages/about">about</a></li>
    </ul>
  
    </nav>
    <div>
    <%= yield %>
    
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title , class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description , class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_field :text , class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image_url %>
    <%= f.text_field :image_url , class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :string %>
    <%= f.text_field :string , class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price , class:"form-control" %>
  </div>

  <div class="actions">
    <%= f.submit :create, class:"btn btn-default"%>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product , class:"btn btn-xs btn-default" %> |
<%= link_to 'Back', products_path , class:"btn btn-xs btn-default"  %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
     
      <th>Image url</th>
      
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= strip_tags(product.description) %></td>
        
        <td><%= image_tag(product.image_url) %></td>
        
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product , class:"btn btn-xs btn-danger" %></td>
        <td><%= link_to 'Edit', edit_product_path(product) , class:"btn btn-xs btn-danger" %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-xs btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path , class:"btn btn-xs btn-danger" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path , class:"btn btn-xs btn-danger" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">

<div class="panel-header">product</div>

<div class="panel-body">


<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>


<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>


<p>
  <strong>Text:</strong>
  <%= @product.text %>
</p>


<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>


<p>
  <strong>String:</strong>
  <%= @product.string %>
</p>


<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>


</div>

<div class="panel-footer">

<%= link_to 'Edit', edit_product_path(@product) ,class:"btn btn-xs btn-danger" %> |
<%= link_to 'Back', products_path , class:"btn btn-xs btn-danger" %>

</div></div>